#!/bin/bash
if [ -z "$1" ]
then
    ctfd_patch="./CTFd"
else
    ctfd_patch=$1
fi

# git clone https://github.com/CTFd/CTFd.git

cp -rf rate_file_by_openai $ctfd_patch/CTFd/plugins/
cp -rf config/openai_config.py $ctfd_patch/CTFd/plugins/rate_file_by_openai/openai_code/app
cp -rf config/criteria.md $ctfd_patch/CTFd/plugins/rate_file_by_openai/openai_code/app

cp -ff src_files/docker-compose.override.yml $ctfd_patch/

# cd CTFd
# docker-compose up